spring.application.name=hotelApi
server.port=8080
server.servlet.context-path=/malvanihotel
jwt.secret=MyJwtSecretKeyForMalvaniHotelApi123456789
jwt.expiration=86400000


spring.datasource.url=jdbc:mysql://localhost:3306/MalvaniDB
spring.datasource.username=root
spring.datasource.password=root@123

#spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db
#spring.datasource.username=root
#spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


